list: $/gviabcua/cron/models/workflow/columns.yaml
modelClass: Gviabcua\Cron\Models\Workflow
title: Workflows
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'gviabcua/cron/workflows/update/:id'
