title: Actions
modelClass: Gviabcua\Cron\Models\Action
list: $/gviabcua/cron/models/action/columns.yaml
recordUrl: 'gviabcua/cron/actions/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
